# Generated by Django 4.1.3 on 2022-11-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=254, verbose_name='Razão Social / Nome')),
                ('nome_fantasia', models.CharField(blank=True, max_length=254, null=True, verbose_name='Nome fantasia')),
                ('inscricao_federal', models.CharField(max_length=20, unique=True, verbose_name='CNPJ / CPF')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=128, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'customer',
            },
        ),
    ]
