# Generated by Django 4.1.3 on 2022-11-28 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('daily_retention', models.PositiveIntegerField(default=1, verbose_name='Retenção diária')),
                ('monthly_retention', models.PositiveIntegerField(default=0, verbose_name='Retenção mensal')),
                ('yearly_retention', models.PositiveIntegerField(default=0, verbose_name='Retenção anual')),
                ('logs_retention', models.PositiveIntegerField(default=1, verbose_name='Retenção dos logs')),
                ('source_folders', models.TextField(default='+/***', help_text='\n    Se pretende copiar determinadas pastas presente em subpastas\n    do caminho definido, deverá montar a estrutura até chegar nela\n    <br>Exemplo:\n    <pre>\n    + /usr/\n    + /usr/local/\n    + /usr/local/bin/***\n    + /var/\n    + /var/spool/\n    + /var/spool/cron/\n    + /var/spool/cron/crontabs/***\n    </pre>\n    Se quer copiar tudo, manda brasa só nesse mesmo\n    <br><pre>+ /***</pre>\n    ')),
                ('additional_parameters', models.CharField(blank=True, help_text="\n    Defina algumas opções adicionais do rsync se precisar.<br>\n    O programa já usa por padrão as opções: '-avihh', '--stats', '--out-format=%i %C %n%L' e '--delete-excluded'.<br>\n    As opções deverão ser separadas por um espaço.<br>\n    Exemplo: <br>\n    <pre>\n    --compress --partial --progress\n    </pre>\n    ", max_length=255, null=True, verbose_name='Parâmetros adicionais do backup')),
                ('report_address', models.EmailField(blank=True, help_text='Quer que o cliente saiba como está o backup dele? Coloque aqui.', max_length=254, null=True, verbose_name='Endereço de notificação')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('active', models.BooleanField(default=True)),
                ('server', models.ForeignKey(help_text='Servidor que este backup pertence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup', to='servers.server')),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
            },
        ),
    ]
