# Generated by Django 4.1.3 on 2022-11-28 16:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descrição')),
                ('ip_address', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Endereço IP')),
                ('ssh_user', models.CharField(default='root', max_length=100, verbose_name='Usuário de autenticação')),
                ('ssh_port', models.PositiveIntegerField(default=4502, verbose_name='Porta SSH')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Criação')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Atualização')),
                ('active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
            },
        ),
    ]
